#!/bin/bash

COMMIT_MSG=`cat $1`

if [[ $COMMIT_MSG =~ ':clock1:' || $COMMIT_MSG =~ 'Merge' ]]; then
  echo ""
else
  exec < /dev/tty
  if [ $? -eq 0 ]; then
    echo "Please enter time tracking for this commit: (ie. 2d 3h 20m) ";
    read timetracking;

    if [ -z "$timetracking" ]; then
        echo "Time tracking is missing..."
        exit 1
    fi
  else
    echo "Please add time tracking for this commit:";
    echo "message :clock1: (ie. 2d 3h 20m)";
    exit 1
  fi

  echo " :clock1: "$timetracking >> $1
fi
